### ISSUE TITLE
undefined method `statements' for #<CamtParser

### ISSUE THREAD

**Issue by turian** [bluesnotred/camt2ofx#4]
This is my first time using bluesnotred, and I am not having success. I have run `bundle install` and then I attempt to convert the CAMT XML file. However, I get the following error

```
camt2ofx.rb:11:in `<main>': undefined method `statements' for #<CamtParser::Format052::Base:0x00007fd4d2c37360> (NoMethodError)
```

How can I troubleshoot this?

**Comment by bluesnotred** [comment]
It appears that your xml file is in CAMT.052 format, while only CAMT.053 _was_ supported.

With the last update 79bd31e97734f4c4fdb2b0fef84506278ceb3178 CAMT.052 should be also supported.
